name: Api Check
on: workflow_call

jobs:
  Check-Api-Change:
    runs-on: ubuntu-latest
    steps:
      - name: install tools
        run: |
          sudo apt-get install quilt -y
          sudo apt-get install universal-ctags -y
      - uses: actions/checkout@v4
        with:
          repository: kuchune/check-tools
          sparse-checkout: |
            apiCheck/deepin-abigail
            apiCheck/fastFilesCompare.json
          sparse-checkout-cone-mode: false
      - run: mv apiCheck/* .
      - name: download lastest code
        uses: actions/checkout@v4
        with:
          path: baseCodeDir
      - working-directory: ./baseCodeDir
        run: |
          if [ -d "debian/patches" ];then
            if [ "`ls -A debian/patches`" != "" ];then
                cp debian/patches . -fr
                quilt push -a || true
            fi
          fi
      - name: download new code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: currentCodeDir
      - working-directory: ./currentCodeDir
        run: |
          if [ -d "debian/patches" ];then
              if [ "`ls -A debian/patches`" != "" ];then
                  cp debian/patches . -fr
                  quilt push -a  || true
              fi
          fi
      - name: check api
        run: |
          ./deepin-abigail -c fastFilesCompare.json | tee api_check.txt
          multi_line_string="
          --- CHECK CHANGE IN <src/frame/window/modules/accounts/accountsdetailwidget.h> ---
            [Del_export_fun] : void DCC_NAMESPACE::accounts::AccountsDetailWidget::resizeDomainUserTipsL
            [Del_fun] : void DCC_NAMESPACE::accounts::AccountsDetailWidget::showEvent(QShowEvent * event) 
            [Chg_exprort_fun] : void resizeDomainUserTipsLabel()
            [Del_fun] : void showEvent(QShowEvent * event)
            [Chg_struct] : <class:DCC_NAMESPACE::accounts::AccountsDetailWidget> below
                del [dcc::widgets::SettingsItem * DCC_NAMESPACE::accounts::AccountsDetailWidget::m_domainUserTipsItem]
                del [DTK_WIDGET_NAMESPACE::DTipLabel * DCC_NAMESPACE::accounts::AccountsDetailWidget::m_domainUserTipsLabel]
          "
          echo "$multi_line_string" | tee api_check.txt
          if [ -e 'api_check.txt' ];then
            check_num=$(cat api_check.txt | grep -c '\[Chg_exprort_fun\|\[Del_export_fun' || true)
            echo "CHECK_NUM=$check_num" >> $GITHUB_ENV
            if [ $check_num -gt 0 ];then
              sed -i '1i API接口检查检测到存在对外接口删除:' api_check.txt
              exit 1
            fi
          fi
      - name: Comment PR
        if: always() && env.CHECK_NUM > 0
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: api_check.txt