name: validate

on: [push, pull_request]

jobs:
  find_yaml_files:
    name: Find yaml files
    outputs:
      files: ${{ steps.find-files.outputs.files }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: damoun/action-find-files@v2
        id: find-files
        with:
          pattern: '.go'
