name: debianCheck
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read
  checks: read

jobs:
  debian-check:
    uses: kuchune/.github/.github/workflows/debian-check.yml@master
    secrets:
      access_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      job_name: "debian-check"
      repository: ${{ github.repository }}
    
