name: ckuxCheck
on: 
    pull_request_target:
        types: [opened, synchronize, reopened]

permissions:
    contents: read
    pull-requests: read
    checks: write

jobs:
    ckux-check:
        uses: kuchune/.github/.github/workflows/ckux-check.yml@develop
        with:
            check-type: "static-check"