name: staticCheck
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  static-check:
    uses: kuchune/.github/.github/workflows/static-check.yml@develop
