name: apiCheck
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Check-Api-Change:
    runs-on: ubuntu-latest
    outputs:
      isFail: ${{ steps.check-api.outputs.isFail }}
    steps:
      - name: install tools
        continue-on-error: true
        run: |
          sudo apt-get install quilt -y
          sudo apt-get install universal-ctags -y
      - continue-on-error: true
        uses: actions/checkout@v4
        with:
          repository: kuchune/check-tools
          sparse-checkout: |
            apiCheck/deepin-abigail
            apiCheck/fastFilesCompare.json
          sparse-checkout-cone-mode: false
      - name: download lastest code
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          path: baseCodeDir
      - continue-on-error: true
        working-directory: ./baseCodeDir
        run: |
          if [ -d "debian/patches" ];then
            if [ "`ls -A debian/patches`" != "" ];then
                cp debian/patches . -fr
                quilt push -a || true
            fi
          fi
      - name: download new code
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: currentCodeDir
      - continue-on-error: true
        working-directory: ./currentCodeDir
        run: |
          if [ -d "debian/patches" ];then
              if [ "`ls -A debian/patches`" != "" ];then
                  cp debian/patches . -fr
                  quilt push -a  || true
              fi
          fi
      - name: check api
        id: check-api
        run: |
          ./apiCheck/deepin-abigail -c ./apiCheck/fastFilesCompare.json | tee api_check.txt
          multi_line_string="
          --- CHECK CHANGE IN <src/frame/window/modules/accounts/accountsdetailwidget.h> ---
            [Del_export_fun] : void DCC_NAMESPACE::accounts::AccountsDetailWidget::resizeDomainUserTipsL
            [Del_fun] : void DCC_NAMESPACE::accounts::AccountsDetailWidget::showEvent(QShowEvent * event) 
            [Del_fun] : void resizeDomainUserTipsLabel()
            [Del_fun] : void showEvent(QShowEvent * event)
            [Chg_struct] : <class:DCC_NAMESPACE::accounts::AccountsDetailWidget> below
                del [dcc::widgets::SettingsItem * DCC_NAMESPACE::accounts::AccountsDetailWidget::m_domainUserTipsItem]
                del [DTK_WIDGET_NAMESPACE::DTipLabel * DCC_NAMESPACE::accounts::AccountsDetailWidget::m_domainUserTipsLabel]
          "
          echo "$multi_line_string" | tee api_check.txt
          logMsg1='''
          <details>
            <summary>详情</summary>
          
          ```ruby
          '''
          logMsg2='''
          ``` 
          </details>
          '''
          resultInfoMsg=$(cat api_check.txt)
          detailUrl="https://github.com/reviews-team-test/infra-settings/blob/master/services/prow/config/jobs/images/api-check/readme.md"
          logMsgHead="> [!WARNING]\n> [[API接口检查]]($detailUrl)\n- 检测到存在对外接口删除和修改;"
          if [ -e 'api_check.txt' ];then
            check_num=$(cat api_check.txt | grep -c '\[Chg_exprort_fun\|\[Del_export_fun' || true)
            if [ $check_num -gt 0 ];then
              echo "isFail=true" >> $GITHUB_OUTPUT
              echo "check_num=$check_num" >> $GITHUB_OUTPUT
              echo -e "${logMsgHead}${logMsg1}${resultInfoMsg}${logMsg2}" | tee comment.txt
              exit 1
            fi
          fi
      - continue-on-error: true
        if: failure() && steps.check-api.outputs.isFail == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: api-check-comment
          path: comment.txt
      - continue-on-error: true
        if: always()
        uses: actions/checkout@v4
        with:
          repository: kuchune/check-tools
          sparse-checkout: |
            common/sendData.py
          sparse-checkout-cone-mode: false
      - continue-on-error: true
        if: always()
        run: |
          python3 common/sendData.py
        env:
          PROJECT: "${{github.repository}}"
          NUMBER: "${{github.event.pull_request.number}}"
          REVISION: "${{github.event.pull_request.head.sha}}"
          RUNID: "${{github.run_id}}"
          JOBSTATUS: "${{job.status}}"
          TESTTYPE: "apiCheck"
          STATUS: ${{ steps.check-api.outputs.isFail == 'true' && '否' || '是' }}
          RESULT: ${{ steps.check-api.outputs.check_num }}
  Post-Check:
    runs-on: ubuntu-latest
    needs: Check-Api-Change
    continue-on-error: true
    if: needs.Check-Api-Change.outputs.isFail == 'true' && failure()
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-check-comment
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: comment.txt
      - name: Add Reviewers to Pull Request
        uses: ryaugusta/pr-add-reviewers-action@v1
        with:
          token: ${{ github.token }}
          reviewers: ckux
