name: debianCheck
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Check-Debian-Prefix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - check_type: modify
            check_keys: "getcap,setcap,lshw,dmidecode"
          - check_type: all
            check_keys: "export,unset"
    steps:
      - continue-on-error: true
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - if: always()
        continue-on-error: true
        uses: kuchune/ci-check-action@debian-prefix-check
      - if: always()
        continue-on-error: true
        uses: kuchune/ci-check-action@debian-version-check
      - if: always()
        continue-on-error: true
        uses: kuchune/ci-check-action@debian-keys-check
        with:
          check_type: ${{ matrix.check_type }}
          check_keys: ${{ matrix.check_keys }}
      - if: always() && hashFiles('comment.txt')
        continue-on-error: true
        uses: kuchune/ci-check-action@post-check
        with:
          comment-file: comment.txt
          reviewers: ckux
      - if: always()
        continue-on-error: true
        uses: kuchune/ci-check-action@send-data
        with:
          testtype: "debianCheck"
          status: ${{ hashFiles('comment.txt') && '否' || '是' }}
          result: ${{ hashFiles('comment.txt') && '1' || '0' }}
      - if: always() && hashFiles('comment.txt')
        run: exit 1