name: apiCheck
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Check-Api-Change:
    runs-on: ubuntu-latest
    steps:
      - continue-on-error: true
        uses: kuchune/ci-check-action@api-check
      - uses: csexton/debugger-action@master
      - if: always() && hashFiles('comment.txt')
        continue-on-error: true
        uses: kuchune/ci-check-action@post-check
        with:
          comment-file: comment.txt
          reviewers: ckux
      - if: always()
        continue-on-error: true
        uses: kuchune/ci-check-action@send-data
        with:
          testtype: "apiCheck"
          status: ${{ hashFiles('comment.txt') && '否' || '是' }}
          result: ${{ hashFiles('comment.txt') && '1' || '0' }}
      - if: always() && hashFiles('comment.txt')
        run: exit 1