name: apiCheck
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Check-Api-Change:
    runs-on: ubuntu-latest
    steps:
      - id: api-check
        continue-on-error: true
        uses: kuchune/ci-check-action@api-check
      - name: post check
        if: steps.api-check.outputs.isFail == 'true' && failure()
        continue-on-error: true
        uses: kuchune/post-check@comment_and_review
        with:
          comment-file: comment.txt
          reviewers: ckux
      - name: send data
        if: always()
        continue-on-error: true
        uses: kuchune/post-check@send_data
        with:
          testtype: "apiCheck"
          status: ${{ steps.api-check.outputs.isFail == 'true' && '否' || '是' }}
          result: ${{ steps.api-check.outputs.isFail == 'true' && steps.api-check.outputs.check_num || '0' }}
      - if: steps.api-check.outputs.isFail == 'true'
        run: exit 1