name: debiancheck
on: [push, pull_request]


jobs:
  debian-check:
    runs-on: ubuntu-latest
    steps:
      - name: Upload Data to MDY
        if: ${{ always() }}
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_type: 'json-extended'
          webhook_url: 'https://cooperation.uniontech.com/api/workflow/hooks/NjY0ZDkzNTFiNTRhZGQ0Mzg1N2Q1MWZh'
          webhook_secret: '8l1O6E0M6Q4sad1O7m3k1RdV9gda3Kea14aK6396a308a1938e7Bfxb3bB5zbD0c'
          data: '{ "name": "hello", "value" : "world" }'