name: debianCheck
on: [push, pull_request_target]
  # - pull_request_target:
  #   branches:
  #     - develop/snipe
  #   paths-ignore:
  #     - ".github/workflows/**"


jobs:
  debian-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '2'
      - name: Check Debian Prefix
        id: check-debian-prefix
        if: steps.checkout.outcome == 'success'
        run: |
          python3 $GITHUB_WORKSPACE/.github/script/debian-check.py --type pre-check --repo $GITHUB_REPOSITORY --pr $GITHUB_PR_NUMBER
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
      - name: Check Specical Words
        id: check-specical-words
        if: steps.checkout.outcome == 'success' && always()
        run: |
          python3 $GITHUB_WORKSPACE/.github/script/debian-check.py --type keys-check --repo $GITHUB_REPOSITORY --PRN $GITHUB_PR_NUMBER --keys $FILTER_KEYS --exclude $EXCLUDE_FILES
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
          FILTER_KEYS: "getcap,setcap,lshw,dmidecode"
          EXCLUDE_FILES: 'js, vue, ts, less, html, go, css, json, txt, doc, jpg, png, svg, py, yml, md'
      - name: Check Env Set Words
        id: check-env-set-words
        if: steps.checkout.outcome == 'success' && always()
        run: |
          python3 $GITHUB_WORKSPACE/.github/script/debian-check.py --type keys-check --repo $GITHUB_REPOSITORY --PRN $GITHUB_PR_NUMBER --keys $FILTER_KEYS --exclude $EXCLUDE_FILES
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
          FILTER_KEYS: "export, unset"
          EXCLUDE_FILES: 'js, vue, ts, less, html, go, css, json, txt, doc, jpg, png, svg, py, yml, md'
