name: Debian Check
on: workflow_call

permissions: write-all

jobs:
  call-debian-check-prefix:
    uses: ./.github/workflows/debian-check-prefix.yml
  call-debian-check-version:
    uses: ./.github/workflows/debian-check-version.yml
  call-debian-check-keys:
    uses: ./.github/workflows/debian-check-keys.yml
  post-debian-check:
    needs: [call-debian-check-prefix, call-debian-check-version, call-debian-check-keys]
    uses: ./.github/workflows/debian-check-post.yml
    secrets: inherit
    with:
      debian-check-prefix-status: ${{ needs.call-debian-check-prefix.outputs.check_status }}
      debian-check-prefix-msg: ${{ needs.call-debian-check-prefix.outputs.check_msg }}
      debian-check-version-status: ${{ needs.call-debian-check-version.outputs.check_status }}
      debian-check-version-msg: ${{ needs.call-debian-check-version.outputs.check_msg }}
      debian-check-key-status-env: ${{ needs.call-debian-check-keys.outputs.check_status_env }}
      debian-check-key-msg-env: ${{ needs.call-debian-check-keys.outputs.check_msg_env}}
      debian-check-key-status: ${{ needs.call-debian-check-keys.outputs.check_status }}
      debian-check-key-msg: ${{ needs.call-debian-check-keys.outputs.check_msg }}