name: Debian Check
on: workflow_call

permissions: write-all

jobs:
  call-debian-prefix-check:
    uses: ./.github/workflows/debian-check-prefix.yml
  call-debian-version-check:
    uses: ./.github/workflows/debian-check-version.yml
  call-specical-words-check:
    uses: ./.github/workflows/debian-check-keys.yml
  # call-env-set-words-check:
  #   uses: ./.github/workflows/debian-check-env.yml
