name: Debian Check
on: workflow_call

permissions: write-all

jobs:
  call-debian-check-prefix:
    uses: ./.github/workflows/debian-check-prefix.yml
  call-debian-check-version:
    uses: ./.github/workflows/debian-check-version.yml
  call-debian-check-keys:
    uses: ./.github/workflows/debian-check-keys.yml
  post-debian-check:
    if: failure()
    needs: [call-debian-check-prefix, call-debian-check-version, call-debian-check-keys]
    runs-on: ubuntu-latest
    steps:
      - uses: ryaugusta/pr-add-reviewers-action@v1
        with:
          token: ${{ secrets.REVIEW_TOKEN }}
          team_reviewers: reiviews-test-team
