name: debianCheck
on: pull_request
  # pull_request:
    # paths-ignore:
    #   - ".github/workflows/**"
permissions: read-all
env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPOSITORY: ${{ github.repository }}
  PULL_NUMBER: ${{ github.event.pull_request.number }}
  EXCLUDE_FILES: "js,vue,ts,less,html,go,css,json,txt,doc,jpg,png,svg,py,yml,md"

jobs:
  debian-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '2'
      - name: Check Debian Prefix
        id: check-debian-prefix
        if: steps.checkout.outcome == 'success'
        run: |
          python3 $GITHUB_WORKSPACE/.github/script/debian-check.py --type pre-check --token $GITHUB_ACCESS_TOKEN --repo $GITHUB_REPOSITORY --pr $PULL_NUMBER
      - name: Check Specical Words
        id: check-specical-words
        if: steps.checkout.outcome == 'success' && always()
        env:
          FILTER_KEYS: "getcap,setcap,lshw,dmidecode"
        run: |
          python3 $GITHUB_WORKSPACE/.github/script/debian-check.py --type keys-check --token $GITHUB_ACCESS_TOKEN --repo $GITHUB_REPOSITORY --pr $PULL_NUMBER --keys $FILTER_KEYS --exclude $EXCLUDE_FILES --log keys.json
      - name: Check Env Set Words
        id: check-env-set-words
        if: steps.checkout.outcome == 'success' && always()
        env:
          FILTER_KEYS: "export,unset"
        run: |
          python3 $GITHUB_WORKSPACE/.github/script/debian-check.py --type keys-check --token $GITHUB_ACCESS_TOKEN --repo $GITHUB_REPOSITORY --pr $PULL_NUMBER --keys $FILTER_KEYS --exclude $EXCLUDE_FILES --log env-keys.json
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            环境设置敏感词检查**${{ steps.check-env-set-words.outcome }}** :wave:
      - name: Publish reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            keys.json
            env-keys.json
