name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Add shellcheck annotator
        uses: pr-annotators/shellcheck-pr-annotator@main

      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          format: gcc