name: staticCheck
on: pull_request


jobs:
  golangcilint:
    name: golangcilint
    runs-on: ubuntu-latest
    steps:
      - run: export
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: mode check
        if: always() && hashFiles('go.mod') == ''
        run: go mod init ${git.repository}
      - name: GolangCILint Check
        if: success()
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58