name: staticCheck
on: pull_request

permissions:
  contents: read
  pull-requests: read
  checks: write
jobs:
  golangcilint:
    name: golangcilint
    runs-on: ubuntu-latest
    steps:
      - run: export
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: mode check
        if: always() && hashFiles('go.mod') == ''
        run: |
          go mod init ${project}
          go mod tidy
        env:
          project: ${{ github.repository }}
      - name: config check
        if: always() && hashFiles('.golangci.yml') == ''
        run: |
          wget -O .golangci.yml https://raw.githubusercontent.com/kuchune/action-cppcheck/main/config/golangci.yml
      - name: GolangCILint Check
        if: success()
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
          args: --out-format=colored-line-number
      - if: always()
        run: echo '::error file=test.go,line=1,col=16::C++ source files not allowed when not using cgo or SWIG(typecheck)'