name: Static Check
on:
  workflow_dispatch:

jobs:
  Call-GolangCiLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: linuxdeepin/linglong-pica
          ref: 29ea5048a28a0a7b480f1face46519256247d255
          persist-credentials: false
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Mod Check
        if: hashFiles('go.mod') == ''
        run: |
          go mod init ${{ github.repository }}
          go mod tidy
      - name: Config check
        if: hashFiles('.golangci.yml') == ''
        uses: actions/checkout@v4
        with:
          repository: kuchune/check-tools
          sparse-checkout: staticCheck/golangci.yml
          sparse-checkout-cone-mode: false
          path: staticCheck
      - if: hashFiles('.golangci.yml') == ''
        run: mv staticCheck/staticCheck/golangci.yml .golangci.yml
      - name: GolangCILint Check
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=10m
          only-new-issues: true
      - if: always()
        uses: csexton/debugger-action@master
