name: Static Check
on: workflow_call

jobs:
  Static-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - name: Get Primary Language
        if: always()
        id: get-primary-language
        uses: fiddlermikey/action-get-primary-language@v2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
      - name: Get Go Files
        id: get-go-files
        uses: SkyHighGrowth/gha-changed-files@v1.0.1
        with:
          files: |
            **.go
      - name: Get C Files
        id: get-c-files
        uses: SkyHighGrowth/gha-changed-files@v1.0.1
        with:
          files: |
            **.cpp
            **.cxx
            **.cc
            **.c++
            **.c
            **.ipp
            **.ixx
            **.tpp
            **.txx
      - name: Get Shell Files
        id: get-shell-files
        uses: SkyHighGrowth/gha-changed-files@v1.0.1
        with:
          files: |
            **.sh
            **.bash
      - name: get-check-flag
        id: get-check-flag
        run: |
          if [ ${{steps.get-primary-language.outputs.primary_language}} == 'Go' && ${{steps.get-go-files-go-files.outputs.all_changed_files}} ];then
            echo "isGo=true" >> $GITHUB_OUTPUT
          fi
          if [ ${{steps.get-primary-language.outputs.primary_language}} == 'C++' && ${{steps.get-c-files.outputs.all_changed_files}} ];then
            echo "isC=true" >> $GITHUB_OUTPUT
          fi
          if [ ${{steps.get-primary-language.outputs.primary_language}} == 'Go' && ${{steps.get-shell-files.outputs.all_changed_files}} ];then
            echo "isShell=true" >> $GITHUB_OUTPUT
          fi          
      - name: Static Check with Go
        if: steps.get-check-flag.outputs.isGo == 'true'
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Mod Check
        if: steps.get-check-flag.outputs.isGo == 'true' && hashFiles('go.mod') == ''
        run: |
          go mod init ${{ github.repository }}
          go mod tidy
      - name: Config check
        if: steps.get-check-flag.outputs.isGo == 'true' && hashFiles('.golangci.yml') == ''
        uses: actions/checkout@v4
        with:
          repository: kuchune/check-tools
          sparse-checkout: staticCheck/golangci.yml
          sparse-checkout-cone-mode: false
      - if: steps.get-check-flag.outputs.isGo == 'true' && hashFiles('.golangci.yml') == ''
        run: mv staticCheck/golangci.yml .golangci.yml
      - name: GolangCILint Check
        if: steps.get-check-flag.outputs.isGo == 'true'
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
      - name: Static Check with C
        if: steps.get-check-flag.outputs.isC == 'true'
        uses: linuxdeepin/action-cppcheck@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          pull_request_id: ${{ github.event.pull_request.number }}
          allow_approve: false
      - uses: pr-annotators/shellcheck-pr-annotator@main
      - name: Static Check with sh
        if: steps.get-check-flag.outputs.isShell == 'true'
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: ${{ steps.get-shell-files.outputs.all_changed_files }}
          format: gcc