name: Static Check
on:
  workflow_dispatch:

jobs:
  Get-Config:
    runs-on: ubuntu-latest
    outputs:
      goFils: ${{ steps.get-go-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: linuxdeepin/linglong-pica
          ref: 29ea5048a28a0a7b480f1face46519256247d255
          persist-credentials: false
          fetch-depth: 2
      - name: Get Go Files
        id: get-go-files
        uses: SkyHighGrowth/gha-changed-files@v1.0.1
        with:
          files: |
            **.go
  Call-GolangCiLint:
    needs: Get-Config
    runs-on: ubuntu-latest
    if: needs.Get-Config.outputs.goFils != ''
    steps:
      - uses: actions/checkout@v3
        with:
          repository: linuxdeepin/linglong-pica
          ref: 29ea5048a28a0a7b480f1face46519256247d255
          persist-credentials: false
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Mod Check
        if: hashFiles('go.mod') == ''
        run: |
          go mod init ${{ github.repository }}
          go mod tidy
      - name: Config check
        if: hashFiles('.golangci.yml') == ''
        uses: actions/checkout@v4
        with:
          repository: kuchune/check-tools
          sparse-checkout: staticCheck/golangci.yml
          sparse-checkout-cone-mode: false
          path: staticCheck
      - if: hashFiles('.golangci.yml') == ''
        run: mv staticCheck/staticCheck/golangci.yml .golangci.yml
      - name: GolangCILint Check
        continue-on-error: true
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=30m --out-format=junit-xml
          only-new-issues: true
  Call-ShellCheck:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
        with:
          ref: 045f1a5608777d64266285a79368f7019b819a38
          persist-credentials: false
      - uses: pr-annotators/shellcheck-pr-annotator@main
      - uses: ludeeus/action-shellcheck@master
        continue-on-error: true
        with:
          severity: error
          format: gcc