name: staticCheck
on: pull_request

permissions:
  contents: read
  pull-requests: read
  checks: write
jobs:
  download-code:
    name: download-code
    runs-on: ubuntu-latest
    steps:
      - run: export
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - name: Get Language
        if: always()
        id: get-language
        run: |
          echo "lang=$(python3 $GITHUB_WORKSPACE/.github/script/getGithubChangeInfo.py)" >> $GITHUB_OUTPUT
      - name: Static Check with Go
        if: steps.get-language.outputs.lang == 'Go'
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Config check
        if: steps.get-language.outputs.lang == 'Go' && success() && hashFiles('go.mod') == ''
        run: |
          go mod init ${project}
          go mod tidy
          if [ ! -f .golangci.yml ];then
            wget -O .golangci.yml https://raw.githubusercontent.com/kuchune/action-cppcheck/main/config/golangci.yml
          fi
        env:
          project: ${{ github.repository }}
      - name: GolangCILint Check
        if: steps.get-language.outputs.lang == 'Go'
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
      - name: Static Check with C
        if: steps.get-language.outputs.lang == 'C++'
        uses: kuchune/action-cppcheck@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          pull_request_id: ${{ github.event.pull_request.number }}
          allow_approve: false
