on:
  workflow_dispatch:
jobs:
  use_api:
    runs-on: ubuntu-latest
    steps:
      - run: |
          const octokit = new Octokit({ auth: 'organization_token' });
          
          # const {
          #   data: { login },
          # } = await octokit.rest.users.getAuthenticated();
          console.log("Hello, %s", octokit);
