name: debianCheck
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  debian-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files
          configuration: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.GITHUB_TOKEN }}","X-GitHub-Api-Version": "2022-11-28","Accept": "application/vnd.github+json"} }'
      - uses: actions/checkout@v4
        with:
          repository: kuchune/check-tools
          sparse-checkout: debianCheck/do-with-data.py
          sparse-checkout-cone-mode: false
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
      - run: |
          python3 debianCheck/do-with-data.py ${check-type} ${check-keys} fetch-api-data-action/data.json
        env:
          check-keys: "getcap setcap lshw dmidecode"
          check-type: "modify"
      - name: Publish reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: response-json
          path: fetch-api-data-action/data.json




      