on:
  workflow_dispatch:
    inputs:
      debian-check-key-status-env:
        required: true
        type: string
        default: |
          检测到敏感词export,unset变动:
          https://github.com/reviews-team-test/test_jenkins/actions/runs/10241638714/artifacts/1774572979

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ inputs.debian-check-key-status-env }}" >> comment.txt
          if [ -e 'comment.txt' ];then
            sed -i '1i [Debian检查]' comment.txt
            cat comment.txt
          fi
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: comment.txt
          pr_number: 4