name: debianCheck
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  debian-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR
        id: get-git-diff
        uses: jsoares/gh-pr-content-checker@master
        with:
          github-token: ${{ github.token }}
          diffDoesNotContain: "dmidecode lshw"
      - run: echo $diff
        env:
         diff: ${{ steps.get-git-diff.outputs.diff }}
