name: CI-apicheck

# on: push
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  repository: ${{ github.repository }}


jobs:
  Check-Api-Change:
    runs-on: ubuntu-latest
    steps:
      - name: install tools
        run: |
          sudo apt-get install quilt -y
          echo "deb [trusted=yes] http://aptly.uniontech.com/pkg/eagle-sp2/release-candidate/ZGVlcGluLWFiaWdhaWwtMDkwMTE2NTc unstable main" >> /etc/apt/sources.list
          echo "deb [trusted=yes] http://pools.uniontech.com/desktop-professional/ eagle main contrib non-free" >> /etc/apt/sources.list
          sudo apt-get update || true
          sudo apt-get install -y deepin-abigail universal-ctag || true
          cat /etc/apt/sources.list
      - name: download lastest code
        uses: actions/checkout@v4
        with:
          path: baseCodeDir
      - working-directory: ./baseCodeDir
        run: |
          if [ -d "debian/patches" ];then
            if [ "`ls -A debian/patches`" != "" ];then
                cp debian/patches . -fr
                quilt push -a || true
            fi
          fi
      - name: download new code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: currentCodeDir
      - working-directory: ./currentCodeDir
        run: |
          if [ -d "debian/patches" ];then
              if [ "`ls -A debian/patches`" != "" ];then
                  cp debian/patches . -fr
                  quilt push -a  || true
              fi
          fi
      - name: check api
        run: |
          wget https://raw.githubusercontent.com/kuchune/.github/master/.github/tools/fastFilesCompare.json
          deepin-abigail -c fastFilesCompare.json | tee api_check.txt
      - name: analysis api result
        run: |
          if [ -f 'api_check.txt' ];then
            if [[ `cat api_check.txt | grep -c '\[Del_export_fun'` != '0' ]];then
              echo "api检测失败,存在接口删除"
              cat api_check.txt
              exit 1
          fi

