name: debianCheck
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  debian-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: git-full-diff
        uses: fernandosmither/git-full-diff@v1.0.2
        with:
          fetch-depth: 0
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
      - name: filter keys and display
        env:
          diff_patch: ${{ steps.git-full-diff.outputs.diff }}
          check_keys: "getcap setcap lshw dmidecode"
        run: |
          echo "$diff_patch" | while IFS= read -r line
          do
            for key in $check_keys
            do
              if [[ $line == *"$key"* ]]; then
                echo "处理行: $line; 敏感词: $key" >> diff.txt
              fi
            done
          done
          if [ -s "diff.txt" ]; then
            echo "=============================="
            echo "检测到存在敏感词:"
            cat diff.txt
            exit 1
          fi