on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${check_msg}" >> comment.txt
          if [ -e 'comment.txt' ];then
            sed -i '1i [Debian检查]' comment.txt
            cat comment.txt
          fi
        env:
          check_msg: |
            检测到敏感词export,unset1111变动:
            https://github.com/reviews-team-test/test_jenkins/actions/runs/10241638714/artifacts/1774572979
      - name: Comment PR
        if: hashFiles('comment.txt')
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: comment.txt