on:
  workflow_dispatch:

env:
  token: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: get-token
        uses: actions/github-script@v6
        with:
          script: |
            global["fetch"] = fetch
            const { Octokit } = require("@octokit/rest");
            const octokit = new Octokit({ 
              auth: process.env.token 
            });
            const { data: { login } } = await octokit.rest.users.getAuthenticated();
            console.log("Hello, %s", octokit);
