on:
  workflow_dispatch:

jobs:
  DbusApi-Check:
    runs-on: ubuntu-latest
    steps:
      - name: download code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - name: install tools
        run: |
          sudo apt install python3-pip golang -y
          sudo pip3 install clang
      - name: download tools
        uses: actions/checkout@v4
        with:
          repository: reviews-team-test/ci_dbus_check
          path: check-tools
      - name: start check
        run: |
          commit_info='
          {
              "repo_name": "${{github.repository}}",
              "branch": "${{github.ref_name}}",
              "committer": "${{github.actor}}",
              "commit_event": "${{github.server_url}}/${{github.repository}}/pull/${{github.run_attempt}}",
              "commit_hash": "${{github.sha}}",
              "commit_event_id": "${{github.run_attempt}}",
              "jenkins_url": "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}/job/${{job.container.id}}",
              "email": "test@test.com"
          }'
          python3 check-tools/main.py --source_directory="." --commit_info_str="${commit_info}" || true
      - name: get specified property result
        id: repository_type
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "result.json"
          prop_path: "scan_result"
      - name: Publish reports
        id: artifact-upload-step
        if: steps.repository_type.outputs.value == 'unpassed'
        uses: actions/upload-artifact@v4
        with:
          name: dbusApi-check-report
          path: dbus_check.log
      - run: |
          if [ ${{steps.repository_type.outputs.value}} == "unpassed" ];then
            echo "[DBUS接口安全检查检测失败](https://github.com/${{github.repository}}/actions/runs/${{ github.run_id }}/artifacts/${{steps.artifact-upload-step.outputs.artifact-id}})" >> comment.txt
            exit 1
          fi
      - name: Comment PR
        if: always() && hashFiles('comment.txt')
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: comment.txt
