on:
  workflow_dispatch:

jobs:
  DbusApi-Check:
    runs-on: ubuntu-latest
    steps:
      - name: download code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - name: install tools
        run: |
          sudo apt install python3-pip golang -y
          sudo pip3 install clang
      - name: download tools
        uses: actions/checkout@v4
        with:
          repository: reviews-team-test/ci_dbus_check
          path: check-tools
      - name: start check
        run: |
          commit_info='
          {
              "repo_name": '"${{github.repository}}"',
              "branch": '"${{github.ref_name}}"',
              "committer": '"${{github.actor}}"',
              "commit_event": '"${{github.server_url}}/${{github.repository}}/pull/${{github.event.pull_request.number}}"',
              "comm"it_hash": '"${{github.sha}}"',
              "commit_event_id": '"${{github.event.pull_request.number}}"',
              "jenkins_url": '"${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_number}}/job/${{github.run_number}}"',
              "email": "test@test.com"
          }'
          python3 check-tools/main.py --source_directory="." --commit_info_str="${commit_info}" || true
