name: debianCheck
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read
  checks: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  debian-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: kuchune/.github
          sparse-checkout: |
            repos/linuxdeepin/dde-file-manager.json
          sparse-checkout-cone-mode: false
      - name: Sync all files
        uses: linuxdeepin/action-sync@main
        with:
          files: "repos/linuxdeepin/dde-file-manager.json"
          message: |
            chore: Sync by ${{ github.event.head_commit.url }}

            sync by github workflow

            Log: none
            Influence: none