name: CI

# on: push
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  repository: ${{ github.repository }}


jobs:
  filter-keys:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - id: git-full-diff
        uses: fernandosmither/git-full-diff@v1.0.2
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
      - name: filter keys and display
        env: 
          diff_patch: ${{ steps.git-full-diff.outputs.diff }}
          check_keys: "getcap setcap lshw dmidecode"
        run: |
          echo "$diff_patch" | while IFS= read -r line
          do
            for key in $check_keys
            do
              if [[ $line == *"$key"* ]]; then
                echo "处理行: $line; 敏感词: $key" >> diff.log
              fi
            done
          done
          if [ -s "diff.log" ]; then
            echo "检测到存在敏感词:"
            cat diff.log
            exit 1
          fi