on:
  workflow_dispatch:

jobs:
  DbusApi-Check:
    runs-on: ubuntu-latest
    steps:
      - name: download code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - name: install tools
        run: |
          sudo apt install clang-7 libclang-dev llvm-7 python3-pip golang -y
          sudo pip3 install clang
      - name: download tools
        uses: actions/checkout@v4
        with:
          repository: reviews-team-test/ci_dbus_check
          path: check-tools
      - name: start check
        run: |
          pwd
          ls -al
          commit_info="
          {
              "repo_name": ${{github.repository}},
              "branch": ${{github.ref_name}}",
              "committer": ${{github.actor}},
              "commit_event": ${{github.server_url}}/${{github.repository}}/pull/${{github.event.pull_request.number}},
              "commit_hash": ${{github.sha}},
              "commit_event_id": ${{github.event.pull_request.number}},
              "jenkins_url": ${{github.server_url}}/job/${{github.workflow}}/${{github.run_number}},
              "email": ""
          }"
          python3 check-tools/main.py --source_directory="." --commit_info_str="${commit_info}" || true
