name: staticCheck
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  Static-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get All Shell Files
        id: changed-shell-files
        uses: SkyHighGrowth/gha-changed-files@v1.0.1
        with:
          files: |
             **.sh
             **.bash
      - name: Static Check with shellcheck
        if: steps.changed-shell-files.outputs.all_changed_files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-shell-files.outputs.all_changed_files }}
        run: |
          sudo apt-get install shellcheck -y
          shellcheck ${ALL_CHANGED_FILES} -f checkstyle > shellcheck.xml || true
          if [ -e 'shellcheck.xml' ];then
            if [ `cat shellcheck.xml | grep -c "severity='error'"` != '0' ];then
              sed -i "1i shellcheck检测存在error:" shellcheck.xml
              exit 1
            fi
          fi
      - name: Comment PR
        if: failure() && hashFiles('shellcheck.xml')
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: shellcheck.xml