name: CI Testing Primary Language
on: [push]

jobs:
  read_type:
    outputs:
      primaryLanguage: ${{ steps.read.outputs.primary_language }}
    runs-on: ubuntu-latest
    name: Detect Primary Language
    steps:
      - name: Read integration_type
        id: read
        uses: fiddlermikey/action-get-primary-language@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
      - name: Display type
        id: display
        run: |
          echo ${{ steps.read.outputs.primary_language}} | tee -a $GITHUB_STEP_SUMMARY

