name: staticCheck
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  Static-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get All Shell Files
        id: changed-shell-files
        uses: SkyHighGrowth/gha-changed-files@v1.0.1
        with:
          files: |
             **.sh
             **.bash
      - name: List all changed files
        env:
            ALL_CHANGED_FILES: ${{ steps.changed-shell-files.outputs.all_changed_files }}
        run: |
            for file in ${ALL_CHANGED_FILES}; do
                echo "$file was changed"
            done
      - name: Static Check with shellcheck
        uses: sudo-bot/action-shellcheck@latest
        with:
            cli-args: "--format=checkstyle --severity=info ${{ steps.changed-shell-files.outputs.all_changed_files }}"