name: debianCheck
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  debian-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Changed Filenames
        id: get-git-diff
        uses: swaglive/action-git-diff@main
        with:
          head-ref: ${{ github.event.pull_request.head.sha || github.event.after || 'HEAD' }}
          base-ref: ${{ github.event.pull_request.base.sha || github.event.before || 'HEAD~1' }}
      - uses: actions/checkout@v4
        with:
          repository: kuchune/check-tools
          sparse-checkout: debianCheck/do-with-data.py
          sparse-checkout-cone-mode: false
          path: ./
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
      - run: |
          python3 do-with-data.py ${check-type} ${check-keys} ${diff-str} 
        env:
          diff-str: ${{ steps.get-git-diff.outputs.json }}
          check-keys: "getcap setcap lshw dmidecode"
          check-type: "modify"




      