name: CI-apicheck

# on: push
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  repository: ${{ github.repository }}


jobs:
  Check-Api-Change:
    runs-on: ubuntu-latest
    steps:
      - name: install tools
        run: |
          sudo apt-get install quilt -y
          wget https://raw.githubusercontent.com/kuchune/.github/master/.github/tools/deepin-abigail
          sudo apt-get install universal-ctags -y || true
      - name: download lastest code
        uses: actions/checkout@v4
        with:
          path: baseCodeDir
      - working-directory: ./baseCodeDir
        run: |
          if [ -d "debian/patches" ];then
            if [ "`ls -A debian/patches`" != "" ];then
                cp debian/patches . -fr
                quilt push -a || true
            fi
          fi
      - name: download new code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: currentCodeDir
      - working-directory: ./currentCodeDir
        run: |
          if [ -d "debian/patches" ];then
              if [ "`ls -A debian/patches`" != "" ];then
                  cp debian/patches . -fr
                  quilt push -a  || true
              fi
          fi
      - name: check api
        run: |
          wget https://raw.githubusercontent.com/kuchune/.github/master/.github/tools/fastFilesCompare.json
          deepin-abigail -c fastFilesCompare.json | tee api_check.txt
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
      - name: analysis api result
        run: |
          if [ -e 'api_check.txt' ];then
            if [ `cat api_check.txt | grep -c '\[Del_export_fun'` != '0' ];then
              echo "api检测失败,存在接口删除"
              cat api_check.txt
              exit 1
          fi


