name: debianCheck
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  debian-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Changed Filenames
        id: git-diff-action
        uses: swaglive/action-git-diff@main
        with:
          head-ref: ${{ github.event.pull_request.head.sha || github.event.after || 'HEAD' }}
      - name: print json diff
        env:
          DIFF: ${{ steps.git-diff-action.outputs.json }}
        run: echo $DIFF